### PR TITLE
Revert import order to fix imported class being not yet defined

### PR DESCRIPTION
**Pull request by flovouin**
## Description

This PR fixes a circular dependency issue following [ESlint-related changes](https://github.com/glideapps/quicktype/commit/79b94e5870ca8a3bdb24128fdba7cf66a7d39815#diff-8a32d456120dfee969ea812346f3b4f2c9dfaccb2ae0781dff1f126ee6a2c744L23) in #2558.

Using `quicktype-core` in my own project crashes at runtime because of this issue since version `23.0.159` with the following error:

```
TypeError: Class extends value undefined is not a constructor or null

      at Object.<anonymous> (../node_modules/quicktype-core/dist/GraphRewriting.js:143:53)
      at Object.<anonymous> (../node_modules/quicktype-core/dist/TypeGraph.js:9:26)
      at Object.<anonymous> (../node_modules/quicktype-core/dist/Type.js:10:21)
      at Object.<anonymous> (../node_modules/quicktype-core/dist/TypeBuilder.js:10:16)
      at Object.<anonymous> (../node_modules/quicktype-core/dist/attributes/StringTypes.js:7:23)
      at Object.<anonymous> (../node_modules/quicktype-core/dist/TypeUtils.js:7:23)
```

There are many ESlint `import/no-cycle` errors being disabled in the codebase. I wouldn't be surprised if other refactored imports were problematic. However fixing this one was enough in my case.

I apologise for the lack of reproduction example and addition of tests. However it seems that only "end to end" tests for each language exist. I did run the existing tests and linter, though.

## Related Issue

This follows the changes in #2558.

## Motivation and Context

I can no longer use `quicktype-core` as a dependency since version `23.0.159`.

## Previous Behaviour / Output

```
TypeError: Class extends value undefined is not a constructor or null

      at Object.<anonymous> (../node_modules/quicktype-core/dist/GraphRewriting.js:143:53)
      at Object.<anonymous> (../node_modules/quicktype-core/dist/TypeGraph.js:9:26)
      at Object.<anonymous> (../node_modules/quicktype-core/dist/Type.js:10:21)
      at Object.<anonymous> (../node_modules/quicktype-core/dist/TypeBuilder.js:10:16)
      at Object.<anonymous> (../node_modules/quicktype-core/dist/attributes/StringTypes.js:7:23)
      at Object.<anonymous> (../node_modules/quicktype-core/dist/TypeUtils.js:7:23)
```

## New Behaviour / Output

My project relying on `quicktype-core` passes its test suite.

## How Has This Been Tested?

I patched the `quicktype-core` distribution in my own project with the change in this PR.

## Screenshots (if appropriate):

N/A

### CODE REVIEW

**Comment by flovouin** [comment]
cc @inferrinizzard and @dvdsgl, who wrote and reviewed #2558.

**Comment by inferrinizzard** [comment]
@flovouin thanks for the PR!
Dependency cycles were definitely something I wanted to address after migrating to ESLint so thank you for starting that effort

>  exposing more utilities in the index.ts file of the package. However the latter requires a lot more work, because there are many utilities that are useful (if not required) when implementing code generation for a new language using quicktype-core.

^ This would probably end up being a better long term path once I finalise a guide on how to more easily create new custom language and behaviours - what specific utilities are you using that aren't exported yet ?

**Comment by dvdsgl** [comment]
@inferrinizzard let's take a look at our automerge settings – this merged itself after failing.

**Comment by flovouin** [comment]
Thanks!

> what specific utilities are you using that aren't exported yet ?

Here's what I found in my codebase:

```typescript
import { RenderContext, Renderer } from 'quicktype-core/dist/Renderer.js';
import { SourcelikeArray } from 'quicktype-core/dist/Source.js';
import { descriptionTypeAttributeKind, propertyDescriptionsTypeAttributeKind } from 'quicktype-core/dist/attributes/Description.js';
import { AcronymStyleOptions } from 'quicktype-core/dist/support/Acronyms.js';
import { ConvertersOptions } from 'quicktype-core/dist/support/Converters.js';
import { removeNullFromType } from 'quicktype-core/dist/TypeUtils.js';
```

**Pull request merged**
