### PR TITLE
fix: add supportsOptionalClassProperties to TypeScriptZod target language

### PR DESCRIPTION
**Pull request by inferrinizzard**
### Summary
Added `supportsOptionalClassProperties` to `TypeScriptZodTargetLanguage` in order to fix handling of optional properties in JSON Schema that are not listed in `required` array.

### JSON Schema
```json
{
  "properties": {
    "foo": { "type": "string" },           // standard string
    "bar": { "type": ["string", "null"] }, // string | null union
    "baz": { "type": "string" },           // string, optional
    "qux": { "type": ["string", "null"] }, // string | null union, optional
  },
  "required": ["foo", "bar"]
}
```

### Old
```ts
export const Schema = z.object({
  foo: z.string(),                               // standard string
  bar: z.union(z.string(), z.null()),            // string | null union
  baz: z.union(z.string(), z.null()).optional(), // string, optional
  qux: z.union(z.string(), z.null()).optional(), // string | null union, optional
})
```

### New
```ts
export const Schema = z.object({
  foo: z.string(),                               // standard string
  bar: z.union(z.string(), z.null()),            // string | null union
  baz: z.string().optional(),                    // string, optional
  qux: z.union(z.string(), z.null()).optional(), // string | null union, optional
})

### CODE REVIEW

**Comment by inferrinizzard** [comment]
CI Test failure looks like #2462

**Comment by dvdsgl** [comment]
Yes, sadly our CI is currently haunted.

**Comment by inferrinizzard** [comment]
@dvdsgl Are you guys looking for more maintainers? Would like to help out if there's space available

**Comment by dvdsgl** [comment]
Yes please!

We're getting desperate: https://replit.com/bounties/@dvdsgl/fix-our-oss-project

Want to see if you can fix CI? I'll pay you the bounty.

**Comment by Adam724** [comment]
Hello. I believe [this PR](https://github.com/glideapps/quicktype/pull/2494) should fix #2462. The failing tests are now passing locally for me on that branch.

**Comment by inferrinizzard** [comment]
@dvdsgl great to hear that the CI issue has finally been fixed - is there a link to the maintainer slack (or is that defunct?)
Would like to chat to some folks to see which areas of the codebase need more effort before jumping on fixing more issues.

**Comment by dvdsgl** [comment]
We don't have a discourse or slack anymore, but we could make a WhatsApp thingy for now: https://chat.whatsapp.com/E3Heqe9Tjl8IBVqpeFMyPp

**Pull request merged**
